/*Generated by WaveMaker Studio*/

package com.testutils.testdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface TestDBProcedureExecutorService {


}


