/*Generated by WaveMaker Studio*/
package com.testutils.testdb.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.testutils.testdb.EmployeeSkillsUtf8UnicodeCi;

/**
 * Specifies methods used to obtain and modify EmployeeSkillsUtf8UnicodeCi related information
 * which is stored in the database.
 */
@Repository("TestDB.EmployeeSkillsUtf8UnicodeCiDao")
public class EmployeeSkillsUtf8UnicodeCiDao extends WMGenericDaoImpl<EmployeeSkillsUtf8UnicodeCi, Integer> {

    @Autowired
    @Qualifier("TestDBTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

