/*Generated by WaveMaker Studio*/

package com.testutils.leave_application_db.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testutils.leave_application_db.service.Leave_Application_DBQueryExecutorService;
import com.testutils.leave_application_db.models.query.*;

@RestController(value = "Leave_Application_DB.QueryExecutionController")
@RequestMapping("/Leave_Application_DB/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private Leave_Application_DBQueryExecutorService queryService;

    @RequestMapping(value = "/queries/testQuery", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Test")
    public TestQueryResponse executeTestQuery(@RequestParam(value = "id") String id, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: testQuery");
        TestQueryResponse _result = queryService.executeTestQuery(id);
        LOGGER.debug("got the result for named query: testQuery, result:{}", _result);
        return _result;
    }

}


