/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TestQueryResponse implements Serializable {


    @ColumnAlias("isActive")
    private Boolean isActive;

    @ColumnAlias("id")
    private Integer id;

    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestQueryResponse)) return false;
        final TestQueryResponse testQueryResponse = (TestQueryResponse) o;
        return Objects.equals(getIsActive(), testQueryResponse.getIsActive()) &&
                Objects.equals(getId(), testQueryResponse.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIsActive(),
                getId());
    }
}
