/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.AccruedElapsedLeaves;

/**
 * Service object for domain model class {@link AccruedElapsedLeaves}.
 */
public interface AccruedElapsedLeavesService {

    /**
     * Creates a new AccruedElapsedLeaves. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on AccruedElapsedLeaves if any.
     *
     * @param accruedElapsedLeaves Details of the AccruedElapsedLeaves to be created; value cannot be null.
     * @return The newly created AccruedElapsedLeaves.
     */
	AccruedElapsedLeaves create(AccruedElapsedLeaves accruedElapsedLeaves);


	/**
	 * Returns AccruedElapsedLeaves by given id if exists.
	 *
	 * @param accruedelapsedleavesId The id of the AccruedElapsedLeaves to get; value cannot be null.
	 * @return AccruedElapsedLeaves associated with the given accruedelapsedleavesId.
     * @throws EntityNotFoundException If no AccruedElapsedLeaves is found.
	 */
	AccruedElapsedLeaves getById(Integer accruedelapsedleavesId) throws EntityNotFoundException;

    /**
	 * Find and return the AccruedElapsedLeaves by given id if exists, returns null otherwise.
	 *
	 * @param accruedelapsedleavesId The id of the AccruedElapsedLeaves to get; value cannot be null.
	 * @return AccruedElapsedLeaves associated with the given accruedelapsedleavesId.
	 */
	AccruedElapsedLeaves findById(Integer accruedelapsedleavesId);


	/**
	 * Updates the details of an existing AccruedElapsedLeaves. It replaces all fields of the existing AccruedElapsedLeaves with the given accruedElapsedLeaves.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on AccruedElapsedLeaves if any.
     *
	 * @param accruedElapsedLeaves The details of the AccruedElapsedLeaves to be updated; value cannot be null.
	 * @return The updated AccruedElapsedLeaves.
	 * @throws EntityNotFoundException if no AccruedElapsedLeaves is found with given input.
	 */
	AccruedElapsedLeaves update(AccruedElapsedLeaves accruedElapsedLeaves) throws EntityNotFoundException;

    /**
	 * Deletes an existing AccruedElapsedLeaves with the given id.
	 *
	 * @param accruedelapsedleavesId The id of the AccruedElapsedLeaves to be deleted; value cannot be null.
	 * @return The deleted AccruedElapsedLeaves.
	 * @throws EntityNotFoundException if no AccruedElapsedLeaves found with the given id.
	 */
	AccruedElapsedLeaves delete(Integer accruedelapsedleavesId) throws EntityNotFoundException;

	/**
	 * Find all AccruedElapsedLeaves matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AccruedElapsedLeaves.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<AccruedElapsedLeaves> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all AccruedElapsedLeaves matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AccruedElapsedLeaves.
     *
     * @see Pageable
     * @see Page
	 */
    Page<AccruedElapsedLeaves> findAll(String query, Pageable pageable);

    /**
	 * Exports all AccruedElapsedLeaves matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the AccruedElapsedLeaves in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the AccruedElapsedLeaves.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

