/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Appraisal;

/**
 * Service object for domain model class {@link Appraisal}.
 */
public interface AppraisalService {

    /**
     * Creates a new Appraisal. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Appraisal if any.
     *
     * @param appraisal Details of the Appraisal to be created; value cannot be null.
     * @return The newly created Appraisal.
     */
	Appraisal create(Appraisal appraisal);


	/**
	 * Returns Appraisal by given id if exists.
	 *
	 * @param appraisalId The id of the Appraisal to get; value cannot be null.
	 * @return Appraisal associated with the given appraisalId.
     * @throws EntityNotFoundException If no Appraisal is found.
	 */
	Appraisal getById(Integer appraisalId) throws EntityNotFoundException;

    /**
	 * Find and return the Appraisal by given id if exists, returns null otherwise.
	 *
	 * @param appraisalId The id of the Appraisal to get; value cannot be null.
	 * @return Appraisal associated with the given appraisalId.
	 */
	Appraisal findById(Integer appraisalId);

    /**
	 * Find and return the Appraisal for given id  if exists.
	 *
	 * @param id value of id; value cannot be null.
	 * @return Appraisal associated with the given inputs.
     * @throws EntityNotFoundException if no matching Appraisal found.
	 */
    Appraisal getByUniqueKeyId(int id)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Appraisal. It replaces all fields of the existing Appraisal with the given appraisal.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Appraisal if any.
     *
	 * @param appraisal The details of the Appraisal to be updated; value cannot be null.
	 * @return The updated Appraisal.
	 * @throws EntityNotFoundException if no Appraisal is found with given input.
	 */
	Appraisal update(Appraisal appraisal) throws EntityNotFoundException;

    /**
	 * Deletes an existing Appraisal with the given id.
	 *
	 * @param appraisalId The id of the Appraisal to be deleted; value cannot be null.
	 * @return The deleted Appraisal.
	 * @throws EntityNotFoundException if no Appraisal found with the given id.
	 */
	Appraisal delete(Integer appraisalId) throws EntityNotFoundException;

	/**
	 * Find all Appraisals matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Appraisals.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Appraisal> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Appraisals matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Appraisals.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Appraisal> findAll(String query, Pageable pageable);

    /**
	 * Exports all Appraisals matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Appraisals in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Appraisal.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

