/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.CompensatoryOff;


/**
 * ServiceImpl object for domain model class CompensatoryOff.
 *
 * @see CompensatoryOff
 */
@Service("Leave_Application_DB.CompensatoryOffService")
public class CompensatoryOffServiceImpl implements CompensatoryOffService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CompensatoryOffServiceImpl.class);


    @Autowired
    @Qualifier("Leave_Application_DB.CompensatoryOffDao")
    private WMGenericDao<CompensatoryOff, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<CompensatoryOff, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
    @Override
	public CompensatoryOff create(CompensatoryOff compensatoryOff) {
        LOGGER.debug("Creating a new CompensatoryOff with information: {}", compensatoryOff);
        CompensatoryOff compensatoryOffCreated = this.wmGenericDao.create(compensatoryOff);
        return compensatoryOffCreated;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public CompensatoryOff getById(Integer compensatoryoffId) throws EntityNotFoundException {
        LOGGER.debug("Finding CompensatoryOff by id: {}", compensatoryoffId);
        CompensatoryOff compensatoryOff = this.wmGenericDao.findById(compensatoryoffId);
        if (compensatoryOff == null){
            LOGGER.debug("No CompensatoryOff found with id: {}", compensatoryoffId);
            throw new EntityNotFoundException(String.valueOf(compensatoryoffId));
        }
        return compensatoryOff;
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public CompensatoryOff findById(Integer compensatoryoffId) {
        LOGGER.debug("Finding CompensatoryOff by id: {}", compensatoryoffId);
        return this.wmGenericDao.findById(compensatoryoffId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Leave_Application_DBTransactionManager")
	@Override
	public CompensatoryOff update(CompensatoryOff compensatoryOff) throws EntityNotFoundException {
        LOGGER.debug("Updating CompensatoryOff with information: {}", compensatoryOff);
        this.wmGenericDao.update(compensatoryOff);

        Integer compensatoryoffId = compensatoryOff.getRecordId();

        return this.wmGenericDao.findById(compensatoryoffId);
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
	@Override
	public CompensatoryOff delete(Integer compensatoryoffId) throws EntityNotFoundException {
        LOGGER.debug("Deleting CompensatoryOff with id: {}", compensatoryoffId);
        CompensatoryOff deleted = this.wmGenericDao.findById(compensatoryoffId);
        if (deleted == null) {
            LOGGER.debug("No CompensatoryOff found with id: {}", compensatoryoffId);
            throw new EntityNotFoundException(String.valueOf(compensatoryoffId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Page<CompensatoryOff> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all CompensatoryOffs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Page<CompensatoryOff> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all CompensatoryOffs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Leave_Application_DB for table CompensatoryOff to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

