/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.CompOff;

/**
 * Service object for domain model class {@link CompOff}.
 */
public interface CompOffService {

    /**
     * Creates a new CompOff. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on CompOff if any.
     *
     * @param compOff Details of the CompOff to be created; value cannot be null.
     * @return The newly created CompOff.
     */
	CompOff create(CompOff compOff);


	/**
	 * Returns CompOff by given id if exists.
	 *
	 * @param compoffId The id of the CompOff to get; value cannot be null.
	 * @return CompOff associated with the given compoffId.
     * @throws EntityNotFoundException If no CompOff is found.
	 */
	CompOff getById(Integer compoffId) throws EntityNotFoundException;

    /**
	 * Find and return the CompOff by given id if exists, returns null otherwise.
	 *
	 * @param compoffId The id of the CompOff to get; value cannot be null.
	 * @return CompOff associated with the given compoffId.
	 */
	CompOff findById(Integer compoffId);


	/**
	 * Updates the details of an existing CompOff. It replaces all fields of the existing CompOff with the given compOff.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on CompOff if any.
     *
	 * @param compOff The details of the CompOff to be updated; value cannot be null.
	 * @return The updated CompOff.
	 * @throws EntityNotFoundException if no CompOff is found with given input.
	 */
	CompOff update(CompOff compOff) throws EntityNotFoundException;

    /**
	 * Deletes an existing CompOff with the given id.
	 *
	 * @param compoffId The id of the CompOff to be deleted; value cannot be null.
	 * @return The deleted CompOff.
	 * @throws EntityNotFoundException if no CompOff found with the given id.
	 */
	CompOff delete(Integer compoffId) throws EntityNotFoundException;

	/**
	 * Find all CompOffs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching CompOffs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<CompOff> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all CompOffs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching CompOffs.
     *
     * @see Pageable
     * @see Page
	 */
    Page<CompOff> findAll(String query, Pageable pageable);

    /**
	 * Exports all CompOffs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the CompOffs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the CompOff.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

