/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Holidays;

/**
 * Service object for domain model class {@link Holidays}.
 */
public interface HolidaysService {

    /**
     * Creates a new Holidays. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Holidays if any.
     *
     * @param holidays Details of the Holidays to be created; value cannot be null.
     * @return The newly created Holidays.
     */
	Holidays create(Holidays holidays);


	/**
	 * Returns Holidays by given id if exists.
	 *
	 * @param holidaysId The id of the Holidays to get; value cannot be null.
	 * @return Holidays associated with the given holidaysId.
     * @throws EntityNotFoundException If no Holidays is found.
	 */
	Holidays getById(Integer holidaysId) throws EntityNotFoundException;

    /**
	 * Find and return the Holidays by given id if exists, returns null otherwise.
	 *
	 * @param holidaysId The id of the Holidays to get; value cannot be null.
	 * @return Holidays associated with the given holidaysId.
	 */
	Holidays findById(Integer holidaysId);


	/**
	 * Updates the details of an existing Holidays. It replaces all fields of the existing Holidays with the given holidays.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Holidays if any.
     *
	 * @param holidays The details of the Holidays to be updated; value cannot be null.
	 * @return The updated Holidays.
	 * @throws EntityNotFoundException if no Holidays is found with given input.
	 */
	Holidays update(Holidays holidays) throws EntityNotFoundException;

    /**
	 * Deletes an existing Holidays with the given id.
	 *
	 * @param holidaysId The id of the Holidays to be deleted; value cannot be null.
	 * @return The deleted Holidays.
	 * @throws EntityNotFoundException if no Holidays found with the given id.
	 */
	Holidays delete(Integer holidaysId) throws EntityNotFoundException;

	/**
	 * Find all Holidays matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Holidays.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Holidays> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Holidays matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Holidays.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Holidays> findAll(String query, Pageable pageable);

    /**
	 * Exports all Holidays matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Holidays in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Holidays.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

