/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Holidays;


/**
 * ServiceImpl object for domain model class Holidays.
 *
 * @see Holidays
 */
@Service("Leave_Application_DB.HolidaysService")
public class HolidaysServiceImpl implements HolidaysService {

    private static final Logger LOGGER = LoggerFactory.getLogger(HolidaysServiceImpl.class);


    @Autowired
    @Qualifier("Leave_Application_DB.HolidaysDao")
    private WMGenericDao<Holidays, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Holidays, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
    @Override
	public Holidays create(Holidays holidays) {
        LOGGER.debug("Creating a new Holidays with information: {}", holidays);
        Holidays holidaysCreated = this.wmGenericDao.create(holidays);
        return holidaysCreated;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Holidays getById(Integer holidaysId) throws EntityNotFoundException {
        LOGGER.debug("Finding Holidays by id: {}", holidaysId);
        Holidays holidays = this.wmGenericDao.findById(holidaysId);
        if (holidays == null){
            LOGGER.debug("No Holidays found with id: {}", holidaysId);
            throw new EntityNotFoundException(String.valueOf(holidaysId));
        }
        return holidays;
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Holidays findById(Integer holidaysId) {
        LOGGER.debug("Finding Holidays by id: {}", holidaysId);
        return this.wmGenericDao.findById(holidaysId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Leave_Application_DBTransactionManager")
	@Override
	public Holidays update(Holidays holidays) throws EntityNotFoundException {
        LOGGER.debug("Updating Holidays with information: {}", holidays);
        this.wmGenericDao.update(holidays);

        Integer holidaysId = holidays.getId();

        return this.wmGenericDao.findById(holidaysId);
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
	@Override
	public Holidays delete(Integer holidaysId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Holidays with id: {}", holidaysId);
        Holidays deleted = this.wmGenericDao.findById(holidaysId);
        if (deleted == null) {
            LOGGER.debug("No Holidays found with id: {}", holidaysId);
            throw new EntityNotFoundException(String.valueOf(holidaysId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Page<Holidays> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Holidays");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Page<Holidays> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Holidays");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Leave_Application_DB for table Holidays to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

