/*Generated by WaveMaker Studio*/

package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

@Service
public class Leave_Application_DBProcedureExecutorServiceImpl implements Leave_Application_DBProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Leave_Application_DBProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("Leave_Application_DBWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;


}


