/*Generated by WaveMaker Studio*/

package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testutils.leave_application_db.models.query.*;

public interface Leave_Application_DBQueryExecutorService {

    TestQueryResponse executeTestQuery(String id);

}


