/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.LeaveTypeRoleMapping;

/**
 * Service object for domain model class {@link LeaveTypeRoleMapping}.
 */
public interface LeaveTypeRoleMappingService {

    /**
     * Creates a new LeaveTypeRoleMapping. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on LeaveTypeRoleMapping if any.
     *
     * @param leaveTypeRoleMapping Details of the LeaveTypeRoleMapping to be created; value cannot be null.
     * @return The newly created LeaveTypeRoleMapping.
     */
	LeaveTypeRoleMapping create(LeaveTypeRoleMapping leaveTypeRoleMapping);


	/**
	 * Returns LeaveTypeRoleMapping by given id if exists.
	 *
	 * @param leavetyperolemappingId The id of the LeaveTypeRoleMapping to get; value cannot be null.
	 * @return LeaveTypeRoleMapping associated with the given leavetyperolemappingId.
     * @throws EntityNotFoundException If no LeaveTypeRoleMapping is found.
	 */
	LeaveTypeRoleMapping getById(Integer leavetyperolemappingId) throws EntityNotFoundException;

    /**
	 * Find and return the LeaveTypeRoleMapping by given id if exists, returns null otherwise.
	 *
	 * @param leavetyperolemappingId The id of the LeaveTypeRoleMapping to get; value cannot be null.
	 * @return LeaveTypeRoleMapping associated with the given leavetyperolemappingId.
	 */
	LeaveTypeRoleMapping findById(Integer leavetyperolemappingId);


	/**
	 * Updates the details of an existing LeaveTypeRoleMapping. It replaces all fields of the existing LeaveTypeRoleMapping with the given leaveTypeRoleMapping.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on LeaveTypeRoleMapping if any.
     *
	 * @param leaveTypeRoleMapping The details of the LeaveTypeRoleMapping to be updated; value cannot be null.
	 * @return The updated LeaveTypeRoleMapping.
	 * @throws EntityNotFoundException if no LeaveTypeRoleMapping is found with given input.
	 */
	LeaveTypeRoleMapping update(LeaveTypeRoleMapping leaveTypeRoleMapping) throws EntityNotFoundException;

    /**
	 * Deletes an existing LeaveTypeRoleMapping with the given id.
	 *
	 * @param leavetyperolemappingId The id of the LeaveTypeRoleMapping to be deleted; value cannot be null.
	 * @return The deleted LeaveTypeRoleMapping.
	 * @throws EntityNotFoundException if no LeaveTypeRoleMapping found with the given id.
	 */
	LeaveTypeRoleMapping delete(Integer leavetyperolemappingId) throws EntityNotFoundException;

	/**
	 * Find all LeaveTypeRoleMappings matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching LeaveTypeRoleMappings.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<LeaveTypeRoleMapping> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all LeaveTypeRoleMappings matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching LeaveTypeRoleMappings.
     *
     * @see Pageable
     * @see Page
	 */
    Page<LeaveTypeRoleMapping> findAll(String query, Pageable pageable);

    /**
	 * Exports all LeaveTypeRoleMappings matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the LeaveTypeRoleMappings in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the LeaveTypeRoleMapping.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

