/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Leaves;

/**
 * Service object for domain model class {@link Leaves}.
 */
public interface LeavesService {

    /**
     * Creates a new Leaves. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Leaves if any.
     *
     * @param leaves Details of the Leaves to be created; value cannot be null.
     * @return The newly created Leaves.
     */
	Leaves create(Leaves leaves);


	/**
	 * Returns Leaves by given id if exists.
	 *
	 * @param leavesId The id of the Leaves to get; value cannot be null.
	 * @return Leaves associated with the given leavesId.
     * @throws EntityNotFoundException If no Leaves is found.
	 */
	Leaves getById(Integer leavesId) throws EntityNotFoundException;

    /**
	 * Find and return the Leaves by given id if exists, returns null otherwise.
	 *
	 * @param leavesId The id of the Leaves to get; value cannot be null.
	 * @return Leaves associated with the given leavesId.
	 */
	Leaves findById(Integer leavesId);

    /**
	 * Find and return the Leaves for given empId  andfiscalYear  andmonth  if exists.
	 *
	 * @param empId value of empId; value cannot be null.
	 * @param fiscalYear value of fiscalYear; value cannot be null.
	 * @param month value of month; value cannot be null.
	 * @return Leaves associated with the given inputs.
     * @throws EntityNotFoundException if no matching Leaves found.
	 */
    Leaves getByEmpIdAndFiscalYearAndMonth(int empId, String fiscalYear, String month)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing Leaves. It replaces all fields of the existing Leaves with the given leaves.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Leaves if any.
     *
	 * @param leaves The details of the Leaves to be updated; value cannot be null.
	 * @return The updated Leaves.
	 * @throws EntityNotFoundException if no Leaves is found with given input.
	 */
	Leaves update(Leaves leaves) throws EntityNotFoundException;

    /**
	 * Deletes an existing Leaves with the given id.
	 *
	 * @param leavesId The id of the Leaves to be deleted; value cannot be null.
	 * @return The deleted Leaves.
	 * @throws EntityNotFoundException if no Leaves found with the given id.
	 */
	Leaves delete(Integer leavesId) throws EntityNotFoundException;

	/**
	 * Find all Leaves matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Leaves.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Leaves> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Leaves matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Leaves.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Leaves> findAll(String query, Pageable pageable);

    /**
	 * Exports all Leaves matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Leaves in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Leaves.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

