/*Generated by WaveMaker Studio*/

package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

import com.testutils.leave_application_db.models.query.*;

@Service
public class Leave_Application_DBQueryExecutorServiceImpl implements Leave_Application_DBQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Leave_Application_DBQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("Leave_Application_DBWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public TestQueryResponse executeTestQuery(String id) {
        Map params = new HashMap(1);

        params.put("id", id);

        return queryExecutor.executeNamedQuery("testQuery", params, TestQueryResponse.class);
    }

}


