/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.LeaveTypeRoleMapping;
import com.testutils.leave_application_db.LeaveTypes;

/**
 * Service object for domain model class {@link LeaveTypes}.
 */
public interface LeaveTypesService {

    /**
     * Creates a new LeaveTypes. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on LeaveTypes if any.
     *
     * @param leaveTypes Details of the LeaveTypes to be created; value cannot be null.
     * @return The newly created LeaveTypes.
     */
	LeaveTypes create(LeaveTypes leaveTypes);


	/**
	 * Returns LeaveTypes by given id if exists.
	 *
	 * @param leavetypesId The id of the LeaveTypes to get; value cannot be null.
	 * @return LeaveTypes associated with the given leavetypesId.
     * @throws EntityNotFoundException If no LeaveTypes is found.
	 */
	LeaveTypes getById(Integer leavetypesId) throws EntityNotFoundException;

    /**
	 * Find and return the LeaveTypes by given id if exists, returns null otherwise.
	 *
	 * @param leavetypesId The id of the LeaveTypes to get; value cannot be null.
	 * @return LeaveTypes associated with the given leavetypesId.
	 */
	LeaveTypes findById(Integer leavetypesId);

    /**
	 * Find and return the LeaveTypes for given name  if exists.
	 *
	 * @param name value of name; value cannot be null.
	 * @return LeaveTypes associated with the given inputs.
     * @throws EntityNotFoundException if no matching LeaveTypes found.
	 */
    LeaveTypes getByName(String name)throws EntityNotFoundException;

    /**
	 * Find and return the LeaveTypes for given displayName  if exists.
	 *
	 * @param displayName value of displayName; value cannot be null.
	 * @return LeaveTypes associated with the given inputs.
     * @throws EntityNotFoundException if no matching LeaveTypes found.
	 */
    LeaveTypes getByDisplayName(String displayName)throws EntityNotFoundException;

	/**
	 * Updates the details of an existing LeaveTypes. It replaces all fields of the existing LeaveTypes with the given leaveTypes.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on LeaveTypes if any.
     *
	 * @param leaveTypes The details of the LeaveTypes to be updated; value cannot be null.
	 * @return The updated LeaveTypes.
	 * @throws EntityNotFoundException if no LeaveTypes is found with given input.
	 */
	LeaveTypes update(LeaveTypes leaveTypes) throws EntityNotFoundException;

    /**
	 * Deletes an existing LeaveTypes with the given id.
	 *
	 * @param leavetypesId The id of the LeaveTypes to be deleted; value cannot be null.
	 * @return The deleted LeaveTypes.
	 * @throws EntityNotFoundException if no LeaveTypes found with the given id.
	 */
	LeaveTypes delete(Integer leavetypesId) throws EntityNotFoundException;

	/**
	 * Find all LeaveTypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching LeaveTypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<LeaveTypes> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all LeaveTypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching LeaveTypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<LeaveTypes> findAll(String query, Pageable pageable);

    /**
	 * Exports all LeaveTypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the LeaveTypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the LeaveTypes.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated leaveTypeRoleMappings for given LeaveTypes id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated LeaveTypeRoleMapping instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<LeaveTypeRoleMapping> findAssociatedLeaveTypeRoleMappings(Integer id, Pageable pageable);

}

