/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Log;


/**
 * ServiceImpl object for domain model class Log.
 *
 * @see Log
 */
@Service("Leave_Application_DB.LogService")
public class LogServiceImpl implements LogService {

    private static final Logger LOGGER = LoggerFactory.getLogger(LogServiceImpl.class);


    @Autowired
    @Qualifier("Leave_Application_DB.LogDao")
    private WMGenericDao<Log, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Log, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
    @Override
	public Log create(Log log) {
        LOGGER.debug("Creating a new Log with information: {}", log);
        Log logCreated = this.wmGenericDao.create(log);
        return logCreated;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Log getById(Integer logId) throws EntityNotFoundException {
        LOGGER.debug("Finding Log by id: {}", logId);
        Log log = this.wmGenericDao.findById(logId);
        if (log == null){
            LOGGER.debug("No Log found with id: {}", logId);
            throw new EntityNotFoundException(String.valueOf(logId));
        }
        return log;
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Log findById(Integer logId) {
        LOGGER.debug("Finding Log by id: {}", logId);
        return this.wmGenericDao.findById(logId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "Leave_Application_DBTransactionManager")
	@Override
	public Log update(Log log) throws EntityNotFoundException {
        LOGGER.debug("Updating Log with information: {}", log);
        this.wmGenericDao.update(log);

        Integer logId = log.getId();

        return this.wmGenericDao.findById(logId);
    }

    @Transactional(value = "Leave_Application_DBTransactionManager")
	@Override
	public Log delete(Integer logId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Log with id: {}", logId);
        Log deleted = this.wmGenericDao.findById(logId);
        if (deleted == null) {
            LOGGER.debug("No Log found with id: {}", logId);
            throw new EntityNotFoundException(String.valueOf(logId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public Page<Log> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Logs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Page<Log> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Logs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service Leave_Application_DB for table Log to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "Leave_Application_DBTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

