/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.OtherLeaveTypes;
import com.testutils.leave_application_db.OtherLeavesRoleMapping;

/**
 * Service object for domain model class {@link OtherLeaveTypes}.
 */
public interface OtherLeaveTypesService {

    /**
     * Creates a new OtherLeaveTypes. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on OtherLeaveTypes if any.
     *
     * @param otherLeaveTypes Details of the OtherLeaveTypes to be created; value cannot be null.
     * @return The newly created OtherLeaveTypes.
     */
	OtherLeaveTypes create(OtherLeaveTypes otherLeaveTypes);


	/**
	 * Returns OtherLeaveTypes by given id if exists.
	 *
	 * @param otherleavetypesId The id of the OtherLeaveTypes to get; value cannot be null.
	 * @return OtherLeaveTypes associated with the given otherleavetypesId.
     * @throws EntityNotFoundException If no OtherLeaveTypes is found.
	 */
	OtherLeaveTypes getById(Integer otherleavetypesId) throws EntityNotFoundException;

    /**
	 * Find and return the OtherLeaveTypes by given id if exists, returns null otherwise.
	 *
	 * @param otherleavetypesId The id of the OtherLeaveTypes to get; value cannot be null.
	 * @return OtherLeaveTypes associated with the given otherleavetypesId.
	 */
	OtherLeaveTypes findById(Integer otherleavetypesId);


	/**
	 * Updates the details of an existing OtherLeaveTypes. It replaces all fields of the existing OtherLeaveTypes with the given otherLeaveTypes.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on OtherLeaveTypes if any.
     *
	 * @param otherLeaveTypes The details of the OtherLeaveTypes to be updated; value cannot be null.
	 * @return The updated OtherLeaveTypes.
	 * @throws EntityNotFoundException if no OtherLeaveTypes is found with given input.
	 */
	OtherLeaveTypes update(OtherLeaveTypes otherLeaveTypes) throws EntityNotFoundException;

    /**
	 * Deletes an existing OtherLeaveTypes with the given id.
	 *
	 * @param otherleavetypesId The id of the OtherLeaveTypes to be deleted; value cannot be null.
	 * @return The deleted OtherLeaveTypes.
	 * @throws EntityNotFoundException if no OtherLeaveTypes found with the given id.
	 */
	OtherLeaveTypes delete(Integer otherleavetypesId) throws EntityNotFoundException;

	/**
	 * Find all OtherLeaveTypes matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OtherLeaveTypes.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<OtherLeaveTypes> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all OtherLeaveTypes matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching OtherLeaveTypes.
     *
     * @see Pageable
     * @see Page
	 */
    Page<OtherLeaveTypes> findAll(String query, Pageable pageable);

    /**
	 * Exports all OtherLeaveTypes matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the OtherLeaveTypes in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the OtherLeaveTypes.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated otherLeavesRoleMappings for given OtherLeaveTypes id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated OtherLeavesRoleMapping instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<OtherLeavesRoleMapping> findAssociatedOtherLeavesRoleMappings(Integer id, Pageable pageable);

}

