/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Test;

/**
 * Service object for domain model class {@link Test}.
 */
public interface TestService {

    /**
     * Creates a new Test. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Test if any.
     *
     * @param test Details of the Test to be created; value cannot be null.
     * @return The newly created Test.
     */
	Test create(Test test);


	/**
	 * Returns Test by given id if exists.
	 *
	 * @param testId The id of the Test to get; value cannot be null.
	 * @return Test associated with the given testId.
     * @throws EntityNotFoundException If no Test is found.
	 */
	Test getById(Integer testId) throws EntityNotFoundException;

    /**
	 * Find and return the Test by given id if exists, returns null otherwise.
	 *
	 * @param testId The id of the Test to get; value cannot be null.
	 * @return Test associated with the given testId.
	 */
	Test findById(Integer testId);


	/**
	 * Updates the details of an existing Test. It replaces all fields of the existing Test with the given test.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Test if any.
     *
	 * @param test The details of the Test to be updated; value cannot be null.
	 * @return The updated Test.
	 * @throws EntityNotFoundException if no Test is found with given input.
	 */
	Test update(Test test) throws EntityNotFoundException;

    /**
	 * Deletes an existing Test with the given id.
	 *
	 * @param testId The id of the Test to be deleted; value cannot be null.
	 * @return The deleted Test.
	 * @throws EntityNotFoundException if no Test found with the given id.
	 */
	Test delete(Integer testId) throws EntityNotFoundException;

	/**
	 * Find all Tests matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Tests.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Test> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Tests matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Tests.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Test> findAll(String query, Pageable pageable);

    /**
	 * Exports all Tests matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Tests in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Test.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

