/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Tmp;

/**
 * Service object for domain model class {@link Tmp}.
 */
public interface TmpService {

    /**
     * Creates a new Tmp. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Tmp if any.
     *
     * @param tmp Details of the Tmp to be created; value cannot be null.
     * @return The newly created Tmp.
     */
	Tmp create(Tmp tmp);


	/**
	 * Returns Tmp by given id if exists.
	 *
	 * @param tmpId The id of the Tmp to get; value cannot be null.
	 * @return Tmp associated with the given tmpId.
     * @throws EntityNotFoundException If no Tmp is found.
	 */
	Tmp getById(Integer tmpId) throws EntityNotFoundException;

    /**
	 * Find and return the Tmp by given id if exists, returns null otherwise.
	 *
	 * @param tmpId The id of the Tmp to get; value cannot be null.
	 * @return Tmp associated with the given tmpId.
	 */
	Tmp findById(Integer tmpId);


	/**
	 * Updates the details of an existing Tmp. It replaces all fields of the existing Tmp with the given tmp.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Tmp if any.
     *
	 * @param tmp The details of the Tmp to be updated; value cannot be null.
	 * @return The updated Tmp.
	 * @throws EntityNotFoundException if no Tmp is found with given input.
	 */
	Tmp update(Tmp tmp) throws EntityNotFoundException;

    /**
	 * Deletes an existing Tmp with the given id.
	 *
	 * @param tmpId The id of the Tmp to be deleted; value cannot be null.
	 * @return The deleted Tmp.
	 * @throws EntityNotFoundException if no Tmp found with the given id.
	 */
	Tmp delete(Integer tmpId) throws EntityNotFoundException;

	/**
	 * Find all Tmps matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Tmps.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Tmp> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Tmps matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Tmps.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Tmp> findAll(String query, Pageable pageable);

    /**
	 * Exports all Tmps matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Tmps in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Tmp.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

