/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.V2;
import com.testutils.leave_application_db.V2Id;

/**
 * Service object for domain model class {@link V2}.
 */
public interface V2Service {

    /**
     * Creates a new V2. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on V2 if any.
     *
     * @param v2 Details of the V2 to be created; value cannot be null.
     * @return The newly created V2.
     */
	V2 create(V2 v2);


	/**
	 * Returns V2 by given id if exists.
	 *
	 * @param v2Id The id of the V2 to get; value cannot be null.
	 * @return V2 associated with the given v2Id.
     * @throws EntityNotFoundException If no V2 is found.
	 */
	V2 getById(V2Id v2Id) throws EntityNotFoundException;

    /**
	 * Find and return the V2 by given id if exists, returns null otherwise.
	 *
	 * @param v2Id The id of the V2 to get; value cannot be null.
	 * @return V2 associated with the given v2Id.
	 */
	V2 findById(V2Id v2Id);


	/**
	 * Updates the details of an existing V2. It replaces all fields of the existing V2 with the given v2.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on V2 if any.
     *
	 * @param v2 The details of the V2 to be updated; value cannot be null.
	 * @return The updated V2.
	 * @throws EntityNotFoundException if no V2 is found with given input.
	 */
	V2 update(V2 v2) throws EntityNotFoundException;

    /**
	 * Deletes an existing V2 with the given id.
	 *
	 * @param v2Id The id of the V2 to be deleted; value cannot be null.
	 * @return The deleted V2.
	 * @throws EntityNotFoundException if no V2 found with the given id.
	 */
	V2 delete(V2Id v2Id) throws EntityNotFoundException;

	/**
	 * Find all V2s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching V2s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<V2> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all V2s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching V2s.
     *
     * @see Pageable
     * @see Page
	 */
    Page<V2> findAll(String query, Pageable pageable);

    /**
	 * Exports all V2s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the V2s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the V2.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

