/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testutils.leave_application_db.Wfh;

/**
 * Service object for domain model class {@link Wfh}.
 */
public interface WfhService {

    /**
     * Creates a new Wfh. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Wfh if any.
     *
     * @param wfh Details of the Wfh to be created; value cannot be null.
     * @return The newly created Wfh.
     */
	Wfh create(Wfh wfh);


	/**
	 * Returns Wfh by given id if exists.
	 *
	 * @param wfhId The id of the Wfh to get; value cannot be null.
	 * @return Wfh associated with the given wfhId.
     * @throws EntityNotFoundException If no Wfh is found.
	 */
	Wfh getById(Integer wfhId) throws EntityNotFoundException;

    /**
	 * Find and return the Wfh by given id if exists, returns null otherwise.
	 *
	 * @param wfhId The id of the Wfh to get; value cannot be null.
	 * @return Wfh associated with the given wfhId.
	 */
	Wfh findById(Integer wfhId);


	/**
	 * Updates the details of an existing Wfh. It replaces all fields of the existing Wfh with the given wfh.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Wfh if any.
     *
	 * @param wfh The details of the Wfh to be updated; value cannot be null.
	 * @return The updated Wfh.
	 * @throws EntityNotFoundException if no Wfh is found with given input.
	 */
	Wfh update(Wfh wfh) throws EntityNotFoundException;

    /**
	 * Deletes an existing Wfh with the given id.
	 *
	 * @param wfhId The id of the Wfh to be deleted; value cannot be null.
	 * @return The deleted Wfh.
	 * @throws EntityNotFoundException if no Wfh found with the given id.
	 */
	Wfh delete(Integer wfhId) throws EntityNotFoundException;

	/**
	 * Find all Wfhs matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Wfhs.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Wfh> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Wfhs matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Wfhs.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Wfh> findAll(String query, Pageable pageable);

    /**
	 * Exports all Wfhs matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Wfhs in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Wfh.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

