/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.testutils.leave_application_db.Audit;

/**
 * Specifies methods used to obtain and modify Audit related information
 * which is stored in the database.
 */
@Repository("Leave_Application_DB.AuditDao")
public class AuditDao extends WMGenericDaoImpl<Audit, Integer> {

    @Autowired
    @Qualifier("Leave_Application_DBTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

