/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Appraisal generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`appraisal`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`id`"})})
public class Appraisal implements Serializable {

    private Integer id;
    private int selfAppraisalId;
    private Boolean isReviewerSubmitted;
    private Boolean isInterviewerSubmitted;
    private Integer reviewerFinalRatingId;
    private Integer interviewerFinalRatingId;
    private String reviewerFinalComments;
    private String interviewerFinalComments;
    private String modifiedBy;
    private Timestamp createdDate;
    private Timestamp lastModifiedDate;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`self_appraisal_id`", nullable = false, scale = 0, precision = 10)
    public int getSelfAppraisalId() {
        return this.selfAppraisalId;
    }

    public void setSelfAppraisalId(int selfAppraisalId) {
        this.selfAppraisalId = selfAppraisalId;
    }

    @Column(name = "`is_reviewer_submitted`", nullable = true)
    public Boolean getIsReviewerSubmitted() {
        return this.isReviewerSubmitted;
    }

    public void setIsReviewerSubmitted(Boolean isReviewerSubmitted) {
        this.isReviewerSubmitted = isReviewerSubmitted;
    }

    @Column(name = "`is_interviewer_submitted`", nullable = true)
    public Boolean getIsInterviewerSubmitted() {
        return this.isInterviewerSubmitted;
    }

    public void setIsInterviewerSubmitted(Boolean isInterviewerSubmitted) {
        this.isInterviewerSubmitted = isInterviewerSubmitted;
    }

    @Column(name = "`reviewer_final_rating_id`", nullable = true, scale = 0, precision = 10)
    public Integer getReviewerFinalRatingId() {
        return this.reviewerFinalRatingId;
    }

    public void setReviewerFinalRatingId(Integer reviewerFinalRatingId) {
        this.reviewerFinalRatingId = reviewerFinalRatingId;
    }

    @Column(name = "`interviewer_final_rating_id`", nullable = true, scale = 0, precision = 10)
    public Integer getInterviewerFinalRatingId() {
        return this.interviewerFinalRatingId;
    }

    public void setInterviewerFinalRatingId(Integer interviewerFinalRatingId) {
        this.interviewerFinalRatingId = interviewerFinalRatingId;
    }

    @Column(name = "`reviewer_final_comments`", nullable = true, length = 1000)
    public String getReviewerFinalComments() {
        return this.reviewerFinalComments;
    }

    public void setReviewerFinalComments(String reviewerFinalComments) {
        this.reviewerFinalComments = reviewerFinalComments;
    }

    @Column(name = "`interviewer_final_comments`", nullable = true, length = 1000)
    public String getInterviewerFinalComments() {
        return this.interviewerFinalComments;
    }

    public void setInterviewerFinalComments(String interviewerFinalComments) {
        this.interviewerFinalComments = interviewerFinalComments;
    }

    @Column(name = "`modified_by`", nullable = true, length = 100)
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Column(name = "`created_date`", nullable = false)
    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "`last_modified_date`", nullable = false)
    public Timestamp getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Timestamp lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Appraisal)) return false;
        final Appraisal appraisal = (Appraisal) o;
        return Objects.equals(getId(), appraisal.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

