/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AttendanceMismatch generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`attendance_mismatch`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`employee_id`", "`mismatched_date`"})})
public class AttendanceMismatch implements Serializable {

    private Integer id;
    private int employeeId;
    private Date mismatchedDate;
    private String status;
    private Boolean isIgnore;
    private Date emailSentDate;
    private String modifiedBy;
    private Timestamp modifiedDate;
    private Timestamp creationDate;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`employee_id`", nullable = false, scale = 0, precision = 10)
    public int getEmployeeId() {
        return this.employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name = "`mismatched_date`", nullable = false)
    public Date getMismatchedDate() {
        return this.mismatchedDate;
    }

    public void setMismatchedDate(Date mismatchedDate) {
        this.mismatchedDate = mismatchedDate;
    }

    @Column(name = "`status`", nullable = true, length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`isIgnore`", nullable = true)
    public Boolean getIsIgnore() {
        return this.isIgnore;
    }

    public void setIsIgnore(Boolean isIgnore) {
        this.isIgnore = isIgnore;
    }

    @Column(name = "`email_sent_date`", nullable = true)
    public Date getEmailSentDate() {
        return this.emailSentDate;
    }

    public void setEmailSentDate(Date emailSentDate) {
        this.emailSentDate = emailSentDate;
    }

    @Column(name = "`modified_by`", nullable = true, length = 100)
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Column(name = "`modified_date`", nullable = false)
    public Timestamp getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Timestamp modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name = "`creation_date`", nullable = false)
    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AttendanceMismatch)) return false;
        final AttendanceMismatch attendanceMismatch = (AttendanceMismatch) o;
        return Objects.equals(getId(), attendanceMismatch.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

