/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpRoles generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`emp_roles`")
@IdClass(EmpRolesId.class)
public class EmpRoles implements Serializable {

    private Integer empId;
    private Integer roleId;
    private Roles roles;

    @Id
    @Column(name = "`Emp_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    @Id
    @Column(name = "`Role_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`Role_ID`", referencedColumnName = "`Role_ID`", insertable = false, updatable = false)
    public Roles getRoles() {
        return this.roles;
    }

    public void setRoles(Roles roles) {
        if(roles != null) {
            this.roleId = roles.getRoleId();
        }

        this.roles = roles;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmpRoles)) return false;
        final EmpRoles empRoles = (EmpRoles) o;
        return Objects.equals(getEmpId(), empRoles.getEmpId()) &&
                Objects.equals(getRoleId(), empRoles.getRoleId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpId(),
                getRoleId());
    }
}

