/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * LeaveTypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`leave_types`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`display_name`"}),
        @UniqueConstraint(columnNames = {"`name`"})})
public class LeaveTypes implements Serializable {

    private Integer id;
    private String name;
    private String displayName;
    private List<LeaveTypeRoleMapping> leaveTypeRoleMappings;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 7)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`name`", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`display_name`", nullable = false, length = 50)
    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.REMOVE, mappedBy = "leaveTypes")
    public List<LeaveTypeRoleMapping> getLeaveTypeRoleMappings() {
        return this.leaveTypeRoleMappings;
    }

    public void setLeaveTypeRoleMappings(List<LeaveTypeRoleMapping> leaveTypeRoleMappings) {
        this.leaveTypeRoleMappings = leaveTypeRoleMappings;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LeaveTypes)) return false;
        final LeaveTypes leaveTypes = (LeaveTypes) o;
        return Objects.equals(getId(), leaveTypes.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

