/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OtherLeavesRoleMapping generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`other_leaves_role_mapping`")
public class OtherLeavesRoleMapping implements Serializable {

    private Integer id;
    private int otherLeaveTypeId;
    private int roleId;
    private Roles roles;
    private OtherLeaveTypes otherLeaveTypes;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`other_leave_type_id`", nullable = false, scale = 0, precision = 7)
    public int getOtherLeaveTypeId() {
        return this.otherLeaveTypeId;
    }

    public void setOtherLeaveTypeId(int otherLeaveTypeId) {
        this.otherLeaveTypeId = otherLeaveTypeId;
    }

    @Column(name = "`role_id`", nullable = false, scale = 0, precision = 10)
    public int getRoleId() {
        return this.roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`role_id`", referencedColumnName = "`Role_ID`", insertable = false, updatable = false)
    public Roles getRoles() {
        return this.roles;
    }

    public void setRoles(Roles roles) {
        if(roles != null) {
            this.roleId = roles.getRoleId();
        }

        this.roles = roles;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`other_leave_type_id`", referencedColumnName = "`id`", insertable = false, updatable = false)
    public OtherLeaveTypes getOtherLeaveTypes() {
        return this.otherLeaveTypes;
    }

    public void setOtherLeaveTypes(OtherLeaveTypes otherLeaveTypes) {
        if(otherLeaveTypes != null) {
            this.otherLeaveTypeId = otherLeaveTypes.getId();
        }

        this.otherLeaveTypes = otherLeaveTypes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof OtherLeavesRoleMapping)) return false;
        final OtherLeavesRoleMapping otherLeavesRoleMapping = (OtherLeavesRoleMapping) o;
        return Objects.equals(getId(), otherLeavesRoleMapping.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

