/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * TestEmployeeDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`test_employee_details`")
public class TestEmployeeDetails implements Serializable {

    private BigInteger id;
    private String firstName;
    private String middleName;
    private String lastName;
    private String shortName;
    private BigInteger departmentId;
    private BigInteger buId;
    private BigInteger roleId;
    private BigInteger managerId;
    private String customerGroupName;
    private Integer customerId;
    private String baseLocation;
    private String workLocation;
    private Integer officeNameId;
    private String cubical;
    private String extension;
    private String homeAddress;
    private String currentAddress;
    private String personalEmail;
    private Date dateOfBirth;
    private Integer experienceInYears;
    private Integer experienceInMonths;
    @Type(type = "DateTime")
    private LocalDateTime dateOfJoining;
    @Type(type = "DateTime")
    private LocalDateTime dateOfLeaving;
    @Type(type = "DateTime")
    private LocalDateTime dateOfResignation;
    @Type(type = "DateTime")
    private LocalDateTime contractEndDate;
    private String mobile;
    private BigInteger projectId;
    private String contractualJobTitle;
    private String nationality;
    private String emergencyContactNo;
    private String emergencyContactRelation;
    private String gender;
    private BigInteger orgLevelId;
    private String bloodGroup;
    private String yammerProfileUrl;
    private String testEmployeeProfilePicLocation;
    private Timestamp createdDate;
    private Timestamp lastModifiedDate;

    @Id
    @Column(name = "`id`", nullable = false, scale = 0, precision = 19)
    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    @Column(name = "`first_name`", nullable = false, length = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "`middle_name`", nullable = true, length = 50)
    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    @Column(name = "`last_name`", nullable = true, length = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "`short_name`", nullable = true, length = 50)
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @Column(name = "`department_id`", nullable = true, scale = 0, precision = 19)
    public BigInteger getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(BigInteger departmentId) {
        this.departmentId = departmentId;
    }

    @Column(name = "`bu_id`", nullable = true, scale = 0, precision = 19)
    public BigInteger getBuId() {
        return this.buId;
    }

    public void setBuId(BigInteger buId) {
        this.buId = buId;
    }

    @Column(name = "`role_id`", nullable = false, scale = 0, precision = 19)
    public BigInteger getRoleId() {
        return this.roleId;
    }

    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }

    @Column(name = "`manager_id`", nullable = true, scale = 0, precision = 19)
    public BigInteger getManagerId() {
        return this.managerId;
    }

    public void setManagerId(BigInteger managerId) {
        this.managerId = managerId;
    }

    @Column(name = "`customer_group_name`", nullable = true, length = 50)
    public String getCustomerGroupName() {
        return this.customerGroupName;
    }

    public void setCustomerGroupName(String customerGroupName) {
        this.customerGroupName = customerGroupName;
    }

    @Column(name = "`customer_id`", nullable = true, scale = 0, precision = 10)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "`base_location`", nullable = true, length = 45)
    public String getBaseLocation() {
        return this.baseLocation;
    }

    public void setBaseLocation(String baseLocation) {
        this.baseLocation = baseLocation;
    }

    @Column(name = "`work_location`", nullable = true, length = 45)
    public String getWorkLocation() {
        return this.workLocation;
    }

    public void setWorkLocation(String workLocation) {
        this.workLocation = workLocation;
    }

    @Column(name = "`office_name_id`", nullable = true, scale = 0, precision = 10)
    public Integer getOfficeNameId() {
        return this.officeNameId;
    }

    public void setOfficeNameId(Integer officeNameId) {
        this.officeNameId = officeNameId;
    }

    @Column(name = "`cubical`", nullable = true, length = 45)
    public String getCubical() {
        return this.cubical;
    }

    public void setCubical(String cubical) {
        this.cubical = cubical;
    }

    @Column(name = "`extension`", nullable = true, length = 15)
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    @Column(name = "`home_address`", nullable = true, length = 500)
    public String getHomeAddress() {
        return this.homeAddress;
    }

    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    @Column(name = "`current_address`", nullable = true, length = 500)
    public String getCurrentAddress() {
        return this.currentAddress;
    }

    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }

    @Column(name = "`personal_email`", nullable = true, length = 100)
    public String getPersonalEmail() {
        return this.personalEmail;
    }

    public void setPersonalEmail(String personalEmail) {
        this.personalEmail = personalEmail;
    }

    @Column(name = "`date_of_birth`", nullable = true)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Column(name = "`experience_in_years`", nullable = true, scale = 0, precision = 10)
    public Integer getExperienceInYears() {
        return this.experienceInYears;
    }

    public void setExperienceInYears(Integer experienceInYears) {
        this.experienceInYears = experienceInYears;
    }

    @Column(name = "`experience_in_months`", nullable = true, scale = 0, precision = 10)
    public Integer getExperienceInMonths() {
        return this.experienceInMonths;
    }

    public void setExperienceInMonths(Integer experienceInMonths) {
        this.experienceInMonths = experienceInMonths;
    }

    @Column(name = "`date_of_joining`", nullable = true)
    public LocalDateTime getDateOfJoining() {
        return this.dateOfJoining;
    }

    public void setDateOfJoining(LocalDateTime dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }

    @Column(name = "`date_of_leaving`", nullable = true)
    public LocalDateTime getDateOfLeaving() {
        return this.dateOfLeaving;
    }

    public void setDateOfLeaving(LocalDateTime dateOfLeaving) {
        this.dateOfLeaving = dateOfLeaving;
    }

    @Column(name = "`date_of_resignation`", nullable = true)
    public LocalDateTime getDateOfResignation() {
        return this.dateOfResignation;
    }

    public void setDateOfResignation(LocalDateTime dateOfResignation) {
        this.dateOfResignation = dateOfResignation;
    }

    @Column(name = "`contract_end_date`", nullable = true)
    public LocalDateTime getContractEndDate() {
        return this.contractEndDate;
    }

    public void setContractEndDate(LocalDateTime contractEndDate) {
        this.contractEndDate = contractEndDate;
    }

    @Column(name = "`mobile`", nullable = true, length = 30)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "`project_id`", nullable = true, scale = 0, precision = 19)
    public BigInteger getProjectId() {
        return this.projectId;
    }

    public void setProjectId(BigInteger projectId) {
        this.projectId = projectId;
    }

    @Column(name = "`contractual_job_title`", nullable = true, length = 50)
    public String getContractualJobTitle() {
        return this.contractualJobTitle;
    }

    public void setContractualJobTitle(String contractualJobTitle) {
        this.contractualJobTitle = contractualJobTitle;
    }

    @Column(name = "`nationality`", nullable = true, length = 50)
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Column(name = "`emergency_contact_no`", nullable = true, length = 30)
    public String getEmergencyContactNo() {
        return this.emergencyContactNo;
    }

    public void setEmergencyContactNo(String emergencyContactNo) {
        this.emergencyContactNo = emergencyContactNo;
    }

    @Column(name = "`emergency_contact_relation`", nullable = true, length = 50)
    public String getEmergencyContactRelation() {
        return this.emergencyContactRelation;
    }

    public void setEmergencyContactRelation(String emergencyContactRelation) {
        this.emergencyContactRelation = emergencyContactRelation;
    }

    @Column(name = "`gender`", nullable = false, length = 15)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "`org_level_id`", nullable = true, scale = 0, precision = 19)
    public BigInteger getOrgLevelId() {
        return this.orgLevelId;
    }

    public void setOrgLevelId(BigInteger orgLevelId) {
        this.orgLevelId = orgLevelId;
    }

    @Column(name = "`blood_group`", nullable = true, length = 5)
    public String getBloodGroup() {
        return this.bloodGroup;
    }

    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    @Column(name = "`yammer_profile_url`", nullable = true, length = 255)
    public String getYammerProfileUrl() {
        return this.yammerProfileUrl;
    }

    public void setYammerProfileUrl(String yammerProfileUrl) {
        this.yammerProfileUrl = yammerProfileUrl;
    }

    @Column(name = "`test_employee_profile_pic_location`", nullable = true, length = 255)
    public String getTestEmployeeProfilePicLocation() {
        return this.testEmployeeProfilePicLocation;
    }

    public void setTestEmployeeProfilePicLocation(String testEmployeeProfilePicLocation) {
        this.testEmployeeProfilePicLocation = testEmployeeProfilePicLocation;
    }

    @Column(name = "`created_date`", nullable = false)
    public Timestamp getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "`last_modified_date`", nullable = false)
    public Timestamp getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Timestamp lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestEmployeeDetails)) return false;
        final TestEmployeeDetails testEmployeeDetails = (TestEmployeeDetails) o;
        return Objects.equals(getId(), testEmployeeDetails.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

