/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TestTable`")
public class TestTable implements Serializable {

    private Integer id;
    private Integer empid;
    private Date toDate;
    private String leaveType;

    @Id
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`empid`", nullable = true, scale = 0, precision = 10)
    public Integer getEmpid() {
        return this.empid;
    }

    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    @Column(name = "`to_date`", nullable = false)
    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    @Column(name = "`leave_type`", nullable = true, length = 45)
    public String getLeaveType() {
        return this.leaveType;
    }

    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TestTable)) return false;
        final TestTable testTable = (TestTable) o;
        return Objects.equals(getId(), testTable.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

