/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tmp generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`tmp`")
public class Tmp implements Serializable {

    private Integer id;
    private String col1;
    private String col2;
    private String col3;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`col1`", nullable = true, length = 255)
    public String getCol1() {
        return this.col1;
    }

    public void setCol1(String col1) {
        this.col1 = col1;
    }

    @Column(name = "`col2`", nullable = true, length = 255)
    public String getCol2() {
        return this.col2;
    }

    public void setCol2(String col2) {
        this.col2 = col2;
    }

    @Column(name = "`col3`", nullable = true, length = 255)
    public String getCol3() {
        return this.col3;
    }

    public void setCol3(String col3) {
        this.col3 = col3;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tmp)) return false;
        final Tmp tmp = (Tmp) o;
        return Objects.equals(getId(), tmp.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

