/*Generated by WaveMaker Studio*/
package com.testutils.leave_application_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Wfh generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`wfh`")
public class Wfh implements Serializable {

    private Integer recordId;
    private int empId;
    private Date fromDate;
    private Date toDate;
    private int days;
    private Boolean holidays;
    private String lastModifiedBy;
    private String recordOwner;
    private Integer relatedEmployee;
    private String status;
    private Integer weekdays;
    private String managerComments;
    private Date dateCreated;
    private Date dateModified;
    private String reason;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`Record_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    @Column(name = "`EmpID`", nullable = false, scale = 0, precision = 10)
    public int getEmpId() {
        return this.empId;
    }

    public void setEmpId(int empId) {
        this.empId = empId;
    }

    @Column(name = "`From_Date`", nullable = false)
    public Date getFromDate() {
        return this.fromDate;
    }

    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    @Column(name = "`To_Date`", nullable = false)
    public Date getToDate() {
        return this.toDate;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    @Column(name = "`Days`", nullable = false, scale = 0, precision = 10)
    public int getDays() {
        return this.days;
    }

    public void setDays(int days) {
        this.days = days;
    }

    @Column(name = "`Holidays`", nullable = true)
    public Boolean getHolidays() {
        return this.holidays;
    }

    public void setHolidays(Boolean holidays) {
        this.holidays = holidays;
    }

    @Column(name = "`Last_Modified_By`", nullable = true, length = 255)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @Column(name = "`Record_Owner`", nullable = true, length = 255)
    public String getRecordOwner() {
        return this.recordOwner;
    }

    public void setRecordOwner(String recordOwner) {
        this.recordOwner = recordOwner;
    }

    @Column(name = "`Related_Employee`", nullable = true, scale = 0, precision = 10)
    public Integer getRelatedEmployee() {
        return this.relatedEmployee;
    }

    public void setRelatedEmployee(Integer relatedEmployee) {
        this.relatedEmployee = relatedEmployee;
    }

    @Column(name = "`Status`", nullable = false, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`Weekdays`", nullable = true, scale = 0, precision = 10)
    public Integer getWeekdays() {
        return this.weekdays;
    }

    public void setWeekdays(Integer weekdays) {
        this.weekdays = weekdays;
    }

    @Column(name = "`Manager_Comments`", nullable = true, length = 255)
    public String getManagerComments() {
        return this.managerComments;
    }

    public void setManagerComments(String managerComments) {
        this.managerComments = managerComments;
    }

    @Column(name = "`Date_Created`", nullable = false)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Column(name = "`Date_Modified`", nullable = false)
    public Date getDateModified() {
        return this.dateModified;
    }

    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }

    @Column(name = "`Reason`", nullable = false, length = 355)
    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Wfh)) return false;
        final Wfh wfh = (Wfh) o;
        return Objects.equals(getRecordId(), wfh.getRecordId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRecordId());
    }
}

